apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoperformance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoperformance
  template:
    metadata:
      labels:
        app: demoperformance
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: demoperformance
        image: demoperformancecontainerregistry2.azurecr.io/demoperformanceapp
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demoperformanceapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
  labels:
    run: demoperformanceapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: demoperformance
