name: CI

# This is a basic workflow to help you get started with Actions
# Global Variables
data:
  AppPrefix: ""
  AppName: "DemoPerformance"
  AppSuffix: "2"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build "
  build:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file Azure Application Insights 
      - name: Deploy Bicep file Azure Application Insights 
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./Bicep/AAI/main.bicep
          parameters: name="{{ AppPrefix }}{{ AppName }}ApplicationInsights{{ AppSuffix }}" location="westeurope"
          failOnStdErr: false

      # Deploy Bicep file Container registry
      - name: Deploy Bicep file Container registry
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./Bicep/ACR/main.bicep
          parameters: name="{{ AppPrefix }}{{ AppName }}ContainerRegistry{{ AppSuffix }}"
          failOnStdErr: false 

      # # Build and push image 
      # - name: 'Build and push image'
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: demoperformancecontainerregistry2.azurecr.io
      #     username: DemoPerformanceContainerRegistry2
      #     password: ZGquDPNmz64TtcsEyiLqz/mfKlfjgENI
      # - run: |
      #     az acr login --name "demoperformancecontainerregistry2"
      #     docker build src/helloworld-service/HelloWorld.API/ -t demoperformancecontainerregistry2.azurecr.io/demoperformanceapp:${{ github.sha }}
      #     docker push demoperformancecontainerregistry2.azurecr.io/demoperformanceapp:${{ github.sha }}

      # - name: 'Deploy to Azure Container Instances'
      #   uses: 'azure/aci-deploy@v1'
      #   with:
      #     resource-group: ${{ secrets.AZURE_RG }}
      #     dns-name-label: ${{ secrets.AZURE_RG }}${{ github.run_number }}
      #     image: demoperformancecontainerregistry2.azurecr.io/demoperformanceapp:${{ github.sha }}
      #     registry-login-server: demoperformancecontainerregistry2.azurecr.io
      #     registry-username: DemoPerformanceContainerRegistry2
      #     registry-password: ZGquDPNmz64TtcsEyiLqz/mfKlfjgENI
      #     name: DemoPerformanceApp
      #     location: 'westeurope'

      # # Deploy Bicep file Kubernetes service
      # - name: Deploy Bicep file Kubernetes service
      #   uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     resourceGroupName: ${{ secrets.AZURE_RG }}
      #     template: ./Bicep/AKS/main.bicep
      #     parameters: name="DemoPerformanceAKSCluster2"
      #     failOnStdErr: false

      # # Deploy Bicep file Azure Log Analytics
      # - name: Deploy Bicep file Azure Log Analytics
      #   uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     resourceGroupName: ${{ secrets.AZURE_RG }}
      #     template: ./Bicep/ALA/main.bicep
      #     parameters: name="DemoPerformanceLogAnalyticsWorkspace2" location="westeurope"
      #     failOnStdErr: false

      # # Deploy Bicep file Azure Load Testing
      # - name: Deploy Bicep file Azure Load Testing
      #   uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     resourceGroupName: ${{ secrets.AZURE_RG }}
      #     template: ./Bicep/ALT/main.bicep
      #     parameters: name="DemoPerformanceLoadTesting2" location="northeurope"
      #     failOnStdErr: false

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: az version

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
